package net.sf.expectit;

import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;

/**
* An executor thread factory which adds a prefix to the default thread name generated by
 * {@link java.util.concurrent.Executors#defaultThreadFactory()}.
*/
final class NamedExecutorThreadFactory implements ThreadFactory {
    private final ThreadFactory defaultFactory = Executors.defaultThreadFactory();
    private final String prefix;

    /**
     * Constructor.
     * @param prefix the string to prepend to the default thread name.
     */
    NamedExecutorThreadFactory(String prefix) {
        this.prefix = prefix;
    }

    @Override
    public Thread newThread(Runnable target) {
        Thread thread = defaultFactory.newThread(target);
        thread.setName(prefix + thread.getName());
        return thread;
    }
}
